import type { Metadata } from "next";
import Link from "next/link";

import { PRIVACY_LAST_UPDATED } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy | ChimAura",
  description: "How ChimAura collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#F7F6F2] text-slate-900 dark:bg-neutral-950 dark:text-slate-100">
      <div className="mx-auto max-w-4xl px-5 py-16 sm:px-8 sm:py-24">
        <Link
          href="/"
          className="mb-10 inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-slate-600 dark:hover:text-slate-300"
        >
          ← Back to home
        </Link>

        <div className="rounded-4xl bg-white/90 p-6 shadow-sm ring-1 ring-black/5 backdrop-blur dark:bg-slate-900/90 dark:ring-white/10 sm:p-8">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#6C63FF]">Legal</p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Privacy Policy</h1>
          <p className="mt-2 text-sm text-slate-400">Last updated: {PRIVACY_LAST_UPDATED}</p>

          <div className="mt-10 max-w-none">
            <Section title="1. Introduction">
              <p>
                ChimAura (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates the ChimAura web application and related services
                (the &ldquo;Service&rdquo;). This Privacy Policy explains how we collect, use, disclose, and safeguard your
                personal information when you use the Service.
              </p>
              <p>
                ChimAura is designed for general wellness and relaxation. It is not a medical device, mental
                health platform, or substitute for professional care.
              </p>
              <p>
                By accessing or using the Service, you agree to the terms of this Privacy Policy. If you do not
                agree, please discontinue use of the Service. This policy is incorporated into our{" "}
                <Link className="text-[#6C63FF] underline" href="/terms">
                  Terms of Service
                </Link>
                .
              </p>
            </Section>

            <Section title="2. Information We Collect">
              <p>
                We collect information you provide directly, information generated by your use of the Service, and
                limited technical data required to operate the Service securely.
              </p>
            </Section>

            <Section title="3. Account and Authentication Data">
              <p>When you register, we collect:</p>
              <ul>
                <li>Email address and display name</li>
                <li>Hashed password (we never store your password in plaintext)</li>
                <li>Email and phone verification status</li>
                <li>Account creation date and session tokens</li>
                <li>Legal consent records: which version of our Terms and Privacy Policy you accepted, and when</li>
              </ul>
            </Section>

            <Section title="4. Wellness, Meditation, Mood, and Journal Data">
              <p>As you use the Service, we store:</p>
              <ul>
                <li>Mood selections and check-in notes you enter</li>
                <li>Meditation session type, duration, voice preference, and completion status</li>
                <li>Breathing exercise sessions and sleep wind-down sessions</li>
                <li>Journal entries (reflections, gratitude logs, free-form notes)</li>
                <li>Daily usage counts (meditations, speech generations, horoscope views)</li>
                <li>Session history, favorites, saved presets, and streak data</li>
                <li>Saved affirmations and prompts you bookmark</li>
              </ul>
              <p>
                This data is used to personalize your experience and is not sold or shared with third parties for
                marketing purposes.
              </p>
            </Section>

            <Section title="5. Horoscope, Zodiac, and Astrological Profile Data">
              <p>
                If you choose to add astrological profile information, we store:
              </p>
              <ul>
                <li>Birthdate and calculated zodiac sign</li>
                <li>Birth time (optional)</li>
                <li>Birth location (city/country text)</li>
                <li>Latitude, longitude, and timezone derived from or provided with birth location</li>
              </ul>
              <p>
                This data is used solely to personalize horoscope and cosmic reflection features within the
                Service. It is not shared with third-party astrology providers in identifiable form.
              </p>
            </Section>

            <Section title="6. AI Processing and Generated Content">
              <p>
                ChimAura uses third-party AI services (currently OpenAI) to generate meditation scripts, voice
                narrations, and related content. Your session inputs (mood, duration, type) are sent to these
                services to produce your personalized session. We do not send your journal entries, astrological
                data, or account details to AI providers unless explicitly required for a feature.
              </p>
              <p>
                AI-generated content is for general wellness and relaxation only. It does not constitute medical
                advice, mental health treatment, or a substitute for professional care.
              </p>
            </Section>

            <Section title="7. Payment and Subscription Data">
              <p>
                Payment processing is handled entirely by Stripe, our third-party payment processor. We do not
                store full card numbers, CVVs, or raw bank details on our servers. We store:
              </p>
              <ul>
                <li>Your Stripe customer ID and subscription ID</li>
                <li>Subscription tier (free or premium), status, billing interval, and current period end</li>
                <li>Billing-related webhook event logs</li>
              </ul>
              <p>
                Stripe&apos;s data practices are governed by the{" "}
                <a
                  className="text-[#6C63FF] underline"
                  href="https://stripe.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Stripe Privacy Policy
                </a>
                .
              </p>
            </Section>

            <Section title="8. Email Delivery and Account Communications">
              <p>We send transactional emails for:</p>
              <ul>
                <li>Email address verification after signup</li>
                <li>Password reset requests</li>
                <li>Billing confirmations and payment failure notices (via Stripe)</li>
                <li>Material changes to our Terms or Privacy Policy</li>
              </ul>
              <p>
                Email delivery is handled by a third-party email provider. We share your email address with
                this provider only as necessary to send these communications. You cannot opt out of strictly
                transactional emails (verification, password reset, billing).
              </p>
            </Section>

            <Section title="9. Push Notifications and Device Data">
              <p>
                If you enable push notifications, we store your browser push subscription endpoint, encryption
                keys, device label (if provided), and platform type. This data is used only to deliver
                notifications you have opted into. You can revoke push notification permission at any time through
                your browser settings or in the app notification preferences.
              </p>
            </Section>

            <Section title="10. Logs, Rate Limiting, IP Hashing, and Security Monitoring">
              <p>
                To operate the Service securely and detect abuse, we collect:
              </p>
              <ul>
                <li>
                  Hashed IP addresses (we apply a one-way hash with a server-side salt; we do not store your raw
                  IP address in most cases)
                </li>
                <li>User-agent strings (browser and OS type)</li>
                <li>API request logs (route, method, status code, timestamp)</li>
                <li>Rate limit counters associated with hashed identifiers</li>
                <li>Webhook event logs from payment processors</li>
              </ul>
              <p>
                These logs are used for fraud prevention, abuse detection, debugging, and capacity planning. They
                are not used for behavioral advertising.
              </p>
            </Section>

            <Section title="11. How We Use Information">
              <p>We use the information we collect to:</p>
              <ul>
                <li>Provide, operate, maintain, and improve the Service;</li>
                <li>Personalize AI-generated meditation and wellness sessions to your mood and preferences;</li>
                <li>Process transactions and manage your subscription;</li>
                <li>Send transactional and account communications;</li>
                <li>Detect, prevent, and address technical issues, fraud, and abuse;</li>
                <li>Comply with applicable legal obligations;</li>
                <li>Enforce our Terms of Service.</li>
              </ul>
            </Section>

            <Section title="12. How We Share Information">
              <p>We do not sell your personal information. We may share your information with:</p>
              <ul>
                <li>
                  <strong>AI content providers</strong> (e.g., OpenAI): Session inputs to generate your personalized
                  meditation content. Governed by their applicable terms.
                </li>
                <li>
                  <strong>Payment processors</strong> (Stripe): Billing and subscription management.
                </li>
                <li>
                  <strong>Email delivery providers:</strong> To send transactional emails on our behalf.
                </li>
                <li>
                  <strong>Cloud infrastructure providers:</strong> Hosting, database, and storage services
                  required to operate the Service.
                </li>
                <li>
                  <strong>Law enforcement or regulators:</strong> When required by law or valid legal process.
                </li>
                <li>
                  <strong>Business transfers:</strong> In connection with a merger, acquisition, or sale of
                  assets, user information may be transferred as a business asset.
                </li>
              </ul>
              <p>
                All third-party service providers are contractually required to use your data only as directed
                by us and in accordance with their own privacy and security obligations.
              </p>
            </Section>

            <Section title="13. Data Retention">
              <p>
                We retain your personal information for as long as your account is active or as needed to
                provide the Service. Specific retention considerations:
              </p>
              <ul>
                <li>Account and session data: retained while your account is active</li>
                <li>Wellness session history and journal entries: retained while your account is active</li>
                <li>API request logs: retained for up to 90 days for security and debugging purposes</li>
                <li>Legal consent records: retained for the lifetime of the account for compliance purposes</li>
                <li>Billing records: retained as required by applicable tax and financial regulations</li>
              </ul>
              <p>
                You may request deletion of your account and associated data at any time by contacting us at{" "}
                <a className="text-[#6C63FF] underline" href="mailto:privacy@chimaura.com">
                  privacy@chimaura.com
                </a>
                . We will fulfill deletion requests within 30 days, except where retention is required by law.
              </p>
            </Section>

            <Section title="14. Your Choices and Data Rights">
              <p>Depending on your jurisdiction, you may have the right to:</p>
              <ul>
                <li>Access the personal information we hold about you;</li>
                <li>Request correction of inaccurate or incomplete data;</li>
                <li>Request deletion of your account and associated data;</li>
                <li>Object to or restrict our processing of your data;</li>
                <li>Receive a portable copy of certain data;</li>
                <li>Withdraw consent (where processing is consent-based);</li>
                <li>Lodge a complaint with a data protection supervisory authority.</li>
              </ul>
              <p>
                To exercise any of these rights, or to request an export or deletion of your data, contact us at{" "}
                <a className="text-[#6C63FF] underline" href="mailto:privacy@chimaura.com">
                  privacy@chimaura.com
                </a>
                . We will respond within 30 days.
              </p>
            </Section>

            <Section title="15. Children and Minors">
              <p>
                The Service is not directed to individuals under the age of 13 (or 16 in the European Economic
                Area). We do not knowingly collect personal information from children. If you believe a child has
                provided us with personal information, please contact us immediately at{" "}
                <a className="text-[#6C63FF] underline" href="mailto:privacy@chimaura.com">
                  privacy@chimaura.com
                </a>{" "}
                and we will promptly delete it.
              </p>
            </Section>

            <Section title="16. Security">
              <p>
                We implement industry-standard administrative, technical, and physical security measures to protect
                your personal information, including password hashing, encrypted sessions, hashed IP identifiers,
                and access controls. However, no method of electronic transmission or storage is 100% secure. We
                cannot guarantee absolute security and encourage you to use a strong, unique password for your
                account.
              </p>
            </Section>

            <Section title="17. International Users">
              <p>
                The Service is operated from the United States. If you are accessing the Service from outside the
                United States, your information may be transferred to and processed in the United States or other
                countries where our service providers operate. By using the Service, you consent to such transfer.
                If you are located in the EEA or UK, we process your data under the legal bases of: performance of
                a contract, legitimate interests (security and fraud prevention), legal obligation, and consent
                where applicable.
              </p>
            </Section>

            <Section title="18. Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. We will notify you of material changes by
                posting the new policy on this page, updating the &ldquo;Last updated&rdquo; date, and sending a notice via
                email or in-app notification. Your continued use of the Service after changes become effective
                constitutes your acceptance of the updated policy.
              </p>
            </Section>

            <Section title="19. Contact">
              <p>
                If you have questions about this Privacy Policy or your data, please contact us at:{" "}
                <a className="text-[#6C63FF] underline" href="mailto:privacy@chimaura.com">
                  privacy@chimaura.com
                </a>
              </p>
              <p>
                See also our{" "}
                <Link className="text-[#6C63FF] underline" href="/terms">
                  Terms of Service
                </Link>
                .
              </p>
            </Section>
          </div>
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="mb-3 text-lg font-semibold text-slate-900 dark:text-slate-100">{title}</h2>
      <div className="space-y-3 text-sm leading-7 text-slate-600 dark:text-slate-400">{children}</div>
    </section>
  );
}
